# Application image configuration
image:
  repository: stratvector
  tag: latest
  pullPolicy: IfNotPresent

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Prometheus configuration
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin
  persistence:
    enabled: true
    size: 10Gi

# Drift detection configuration
driftDetection:
  schedule: "0 */6 * * *"  # Every 6 hours
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Storage configuration
persistence:
  enabled: true
  size: 20Gi
  storageClass: standard 