apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stratvector
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: stratvector
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }} 